my_rest/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/',include('rangi.api.urls',namespace="api")),
    url(r'^home/',include('rangi.urls')),

]

rangi/api/urls.py
from django.conf.urls import url
from .views import CompanyApiView,RangiApiView,CompanyRudApiView,RangiRudApiView

app_name = "rangi"

urlpatterns = [
    # the RUD view must be followed by a pk value to view one object alone

    url(r'^company/(?P<pk>[0-9]+)$',CompanyRudApiView.as_view(),name="company-list"),
    url(r'^rangi/(?P<pk>[0-9]+)$',RangiRudApiView.as_view(),name="rangi-list"),
    url(r'^company/$',CompanyApiView.as_view(),name="company-create"),
    url(r'^rangi/$',RangiApiView.as_view(),name="rangi-create"),

]

rangi/urls.py
from django.conf.urls import url
from .views import home,CreateUser,CreateRangi,CreateCompany


urlpatterns = [
    url(r'^$',home.as_view(),name='home'),
    url(r'^register/$',CreateUser.as_view(),name='user_create'),
    url(r'^rangi/$',CreateRangi.as_view(),name='rangi-create'),
    url(r'^company/$',CreateCompany.as_view(),name='company-create'),




]

rangi/models.py
from django.db import models
from rest_framework.reverse import reverse as api_reverse

# Create your models here.
class Company(models.Model):
    company_name = models.CharField(max_length=100)
    location = models.CharField(max_length=120)

    def __str__(self):
        return self.company_name

        # add the request as an argument inorder to get the actual url

    def get_api_url(self, request=None):
        return api_reverse('api:company-list', kwargs={"pk": self.pk}, request=request)


class Rangi(models.Model):
    color_type = models.CharField(max_length=150)
    rangi = models.CharField(max_length=100)
    brand = models.ForeignKey(Company,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.color_type

    def get_api_url(self, request=None):
        return api_reverse('api:rangi-list', kwargs={"pk": self.pk}, request=request)

rangi/api/views.py
from rest_framework import generics, mixins
from .serializers import CompanySerializer, RangiSerializer
from rangi.models import Rangi, Company
from rest_framework.permissions import AllowAny


# this shows all the companies that are created
# this for adding a new company
class CompanyApiView(mixins.CreateModelMixin, generics.ListAPIView):
    lookup_field = 'pk'
    serializer_class = CompanySerializer
    permission_classes =(AllowAny,)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

    def get_queryset(self):
        return Company.objects.all()


# this view shows all the rangis that are there in the database
# This for creating a new Rangi
class RangiApiView(mixins.CreateModelMixin, generics.ListAPIView):
    lookup_field = 'pk'
    serializer_class = RangiSerializer
    permission_classes = (AllowAny,)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

    def get_queryset(self):
        return Rangi.objects.all()


# opens one object at a time
# The endpoints now
class CompanyRudApiView(generics.RetrieveUpdateDestroyAPIView):
    lookup_field = 'pk'
    serializer_class = CompanySerializer
    permission_classes = (AllowAny,)

    def get_queryset(self):
        return Company.objects.all()

    def get_serializer_context(self, *args, **kwargs):
        return {"request": self.request}


# this view opens one object at a time
# The endpoints now
class RangiRudApiView(generics.RetrieveUpdateDestroyAPIView):
    lookup_field = 'pk'
    serializer_class = RangiSerializer
    permission_classes = (AllowAny,)

    def get_queryset(self):
        return Rangi.objects.all()

    def get_serializer_context(self, *args, **kwargs):
        return {"request": self.request}

rangi/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt,csrf_protect,ensure_csrf_cookie
from django.views.generic import View,UpdateView
from .models import Company,Rangi
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.utils.decorators import method_decorator


# Create your views here.

class home(View):
    model = Company
    template_name = 'rangi/home.html'

    def get(self, request):
        form = self.model(None)
        return render(request, self.template_name, {'form': form})


class CreateRangi(View):
    template_name = "rangi/create_rangi.html"
    def get(self,request):
        company = Company.objects.all()

        return render(request,self.template_name,{'company':company})

    def post(self,request):
        color_type = request.POST['color_type']
        rangi = request.POST['rangi']
        brandId = request.POST['brand']
        brand =  Company.objects.get(id = brandId)
        print(brand)
        Rangi.objects.create(
            color_type = color_type,
            rangi = rangi,
            brand = brand
        )

        return HttpResponse('')

class CreateCompany(View):

    template_name = "rangi/create_company.html"
    def get(self,request):

        return render(request,self.template_name)

    def post(self,request):

        company_name = request.POST['company_name']
        print(company_name)
        location = request.POST['location']
        Company.objects.create(
            company_name = company_name,
            location=location,
        )

        return HttpResponse('')


class CreateUser(View):
    template_name = 'rangi/register.html'

    def get(self,request):
        return render(request,'rangi/register.html')

    @method_decorator(ensure_csrf_cookie, name="dispatch")
    def post(self, request):
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        message = "Ready to process this. Username is " + username + ", Email is " + email + " and password is *****"

        # User.objects.create(
        #     username = username,
        #     email = email,
        #     password = password
        # )
        print(message)
        return HttpResponse("passed")

rangi/templates/rangi/create_company.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form id = "user_form">
    {% csrf_token %}
    <label for="company_name">Company Name</label>
    <input id="company_name" type="text">

    <label for="location">Location</label>
    <input id="location" type="text">

    <input type="submit" value="submit">
</form>

</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
    $(document).on('submit','form#user_form',function (e) {
        e.preventDefault();
        $.ajax({
            type:'POST',
            url : '',
            data :{
                company_name : $('#company_name').val(),
                location : $('#location').val(),
                csrfmiddlewaretoken : $('input[name = csrfmiddlewaretoken]').val()

            },
            success:function () {
                alert("its succesful");
            },
            error:function () {
                alert("Not succesful");

            }

        })

    }
    )

</script>
</html>

rangi/templates/rangi/create_rangi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ajax | register</title>
</head>
<body>
<h1>Here is registration.</h1>
<form id = 'user_form'>
    {% csrf_token %}
    <div>
        <input id = "username" type="text">
        <label for="username">Color Type</label>
    </div>
    <div>
        <input id = "email" type="text">
        <label for="email">color</label>
    </div>
    <div>
        <select id = "company">
                {% for i in company %}

                    <option value="{{i.id}}">{{ i }}</option>
                {% endfor %}
        </select>
        <label for="company">Brand</label>
    </div>
    <div>
        <input type="submit" value="submit">
    </div>

</form>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>

   {% comment %} document.addEventListener("DOMContentLoaded",loadcompany);
    function loadcompany(){

    }{% endcomment %}
    $(document).on('submit','form#user_form',function (e) {
        e.preventDefault();
        console.log($('#company').val());
        $.ajax({
            type:'POST',
            url : '',

            data : {
                color_type : $('#username').val(),
                rangi : $('#email').val(),
                brand : $('#company').val(),
                csrfmiddlewaretoken : $('input[name = csrfmiddlewaretoken]').val()
            },
            success:function(){
                alert("New Rangi succesfully created");
        },
        error:function () {
                alert("Something is wrong with your forms")

        }

        });

    })

</script>
</html>

rangi/templates/rangi/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ajax | welcome</title>
</head>
<body>
<button id="button">Get company</button>
<h1>List of companies.</h1>
<div id = "companies">

</div>

</body>
<script>
    document.getElementById('button').addEventListener('click',loadcompany);
    function loadcompany() {
        var xhr = new XMLHttpRequest();
        xhr.open('GET','{% url 'rangi:rangi-create' %}',true);

        xhr.onload = function () {
            if (this.status == 200){
                var companies = JSON.parse(this.responseText);
                output = '';

                for (var i in companies){
                    output += '<div class ="companies">' +
                            '<ul>' +
                            '<li> ID :'+companies[i].color_type+'</li>' +
                            '<li> ID :'+companies[i].rangi+'</li>' +
                            '</ul>' +
                            '</div>';
                }

                document.getElementById('companies').innerHTML = output;

            }
        }
        xhr.send();
    }
</script>
</html>

rangi/templates/rangi/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>ajax | register</title>

        {# include favicon#}
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    </head>
    <body>
        <h1>Here is registration.</h1>
        <form method="post" action="{% url 'user_create' %}" class="registerUser" id = "user_form">
            {% csrf_token %}
            <div>
                <input id = "username" type="text" name="username">
                <label for="username">Username</label>
            </div>
            <div>
                <input id = "email" type="email" name="email">
                <label for="email">Email</label>
            </div>
            <div>
                <input id = "password" type="password" name="password">
                <label for="password">Password</label>
            </div>
            <div>
                <input type="submit" value="submit">
            </div>

        </form>
    </body>
    <footer>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        {#for submission#}
        <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    </footer>
</html>